name: Build Linux CUDA Wheel

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install CUDA
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get install -y cuda-toolkit-12-5  # Change to your CUDA version if different (check with 'nvcc --version' on your Linux system)

      - name: Install build dependencies
        run: python -m pip install --upgrade pip wheel setuptools cibuildwheel cmake

      - name: Build wheel
        env:
          CMAKE_ARGS: "-DGGML_CUDA=on"
          CIBW_BUILD: cp312-manylinux_x86_64
          CIBW_ARCHS: x86_64
          CIBW_BUILD_VERBOSITY: 3
          CIBW_ENVIRONMENT: "PATH=/usr/local/cuda-12.5/bin:$PATH LD_LIBRARY_PATH=/usr/local/cuda-12.5/lib64:$LD_LIBRARY_PATH"  # Adjust CUDA version to match installed
        run: cibuildwheel --output-dir wheelhouse --platform linux

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/*.whl
