name: Build Windows CPU Wheel

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: python -m pip install --upgrade pip wheel setuptools cibuildwheel

      - name: Build wheel
        env:
          CIBW_BUILD: cp312-win_amd64
          CIBW_ARCHS: amd64
          CIBW_BUILD_VERBOSITY: 3
        run: cibuildwheel --output-dir wheelhouse --platform windows

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/*.whl
