name: Build Linux CUDA Wheel

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install CUDA
        run: |
          sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/3bf863cc.pub
          sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/ /" -y
          sudo apt-get update
          sudo apt-get install -y cuda-toolkit-12-5  # Change to your local CUDA version (e.g., cuda-toolkit-12-1); check with 'nvcc --version' or 'nvidia-smi' on your Linux system

      - name: Install build dependencies
        run: python -m pip install --upgrade pip wheel setuptools cibuildwheel cmake

      - name: Build wheel
        env:
          CMAKE_ARGS: "-DGGML_CUDA=on"
          CIBW_BUILD: cp312-manylinux_x86_64
          CIBW_ARCHS: x86_64
          CIBW_BUILD_VERBOSITY: 3
          CIBW_ENVIRONMENT: "PATH=/usr/local/cuda-12.5/bin:$PATH LD_LIBRARY_PATH=/usr/local/cuda-12.5/lib64:$LD_LIBRARY_PATH"  # Adjust CUDA version to match installed (e.g., cuda-12.1)
        run: cibuildwheel --output-dir wheelhouse --platform linux

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/*.whl
